name: CI demo code 2

on:
  workflow_dispatch: # Manual triggering

env:
  SOURCE_REPO: test-repo-A

jobs:
  sync-code:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source repository (test-repo-A)
      - name: Checkout ${{ env.SOURCE_REPO }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Get the latest commit hash
      - name: Get latest commit hash
        id: commit
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      # Set up Git configuration
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Clone the target repository (test-repo-B) into a fixed directory
      - name: Sync to test-repo-B dev branch
        run: |
          git clone https://x-access-token:${{ secrets.BOILERPLATE_CODE_SYNC_PAT }}@github.com/sivaRoddavarapu/test-repo-B.git
          cd test-repo-B
          git checkout dev || git checkout -b dev
          rsync -av --exclude='.git/' ../test-repo-A/ . # Sync all files except .git
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit for test-repo-B."
          else
            git commit -m "Sync from test-repo-A dev branch - commit ${{ env.COMMIT_HASH }}"
            git push origin dev
          fi
